apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cut-dataset-bkp
spec:
  dataSource:
    name: cut-dataset
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 120Gi
  storageClassName: shared
