apiVersion: v1
kind: Pod
metadata:
  name: jupyter
spec:
  containers:
    - name: jupyter
      image: jupyter/datascience-notebook:python-3.9.13
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8888
      volumeMounts:
        - name: data-volume
          mountPath: /home/jovyan/data
        - name: cut-data-volume
          mountPath: /home/jovyan/cut-data
        - name: metadata-volume
          mountPath: /home/jovyan/metadata
        - name: models-volume
          mountPath: /home/jovyan/models
        - name: notebooks-volume
          mountPath: /home/jovyan/notebooks
      resources:
        requests:
          cpu: "26"
          memory: 16Gi
        limits:
          cpu: "26"
          memory: 64Gi
  nodeSelector:
    cpuclass: epyc
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: dataset
    - name: cut-data-volume
      persistentVolumeClaim:
        claimName: cut-dataset
    - name: metadata-volume
      persistentVolumeClaim:
        claimName: metadata
    - name: models-volume
      persistentVolumeClaim:
        claimName: models
    - name: notebooks-volume
      persistentVolumeClaim:
        claimName: notebooks
