apiVersion: v1
kind: Pod
metadata:
  name: jupyter
spec:
  containers:
    - name: jupyter
      image: jupyter/datascience-notebook:python-3.9.13
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8888
      volumeMounts:
        - name: data-volume
          mountPath: /home/data
        - name: cut-data-volume
          mountPath: /home/cut-data
        - name: metadata-volume
          mountPath: /home/metadata
        - name: models-volume
          mountPath: /home/models          
        - name: notebooks-volume
          mountPath: /home/notebooks
      resources:
        requests:
          cpu: "12"
          memory: 16Gi
        limits:
          cpu: "24"
          memory: 32Gi
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: dataset
    - name: cut-data-volume
      persistentVolumeClaim:
        claimName: cut-dataset
    - name: metadata-volume
      persistentVolumeClaim:
        claimName: metadata
    - name: models-volume
      persistentVolumeClaim:
        claimName: models        
    - name: notebooks-volume
      persistentVolumeClaim:
        claimName: notebooks
